### ISSUE TITLE
UndefinedFunctionError during start-up of retriever

### ISSUE THREAD

**Issue by blaketan** [kipcole9/money#35]
Environment: Elixir 1.5.2, OTP 20.1, ex_money 0.8.2

With the following config:
```
config :ex_money,
  exchange_rate_service: true,
  exchange_rates_retrieve_every: 3_600_000,
  open_exchange_rates_app_id: "APP_ID",
  log_success: :debug
```

this occurs during application startup
```
2017-11-09 15:09:38.304 [warn] Starting exchange rate retrieval service
2017-11-09 15:09:38.304 [warn] Initializing retrieval module Money.ExchangeRates.OpenExchangeRates
2017-11-09 15:09:38.305 [warn] Rates will be retrieved in 1 seconds and then every 3600 seconds.
2017-11-09 15:09:38.349 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:71: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:56: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:50: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 1000, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
2017-11-09 15:09:39.728 [debug] Retrieved exchange rates successfully
```

I was able to get the call `Money.ExchangeRates.latest_rates` after the last log message.

**Comment by kipcole9** [comment]
@blaketan Thanks for the error report.  Looks like you're not on the most recent version?  If you run `mix hex.outdated` can you let me know what you see for `ex_cldr`, `ex_cldr_numbers` and `ex_money`?

Your report did help me identify a spurious log message I was sending when there is a retrieval error so I have pushed `ex_money` version 0.8.3 which is now the latest.

**Comment by blaketan** [comment]
@kipcole9 
Running mix hex.outdated with ex_money 0.82 did not give me any values for the above packages.
```
 mix hex.outdated ex_money                                                                                                                                                          There is newer version of the dependency available 0.8.3 > 0.8.2!

Source  Requirement  

A green requirement means that it matches the latest version.
```

Current versions of dependencies:
```
  decimal 1.4.1
  ex_abnf 0.3.0
  ex_cldr 0.12.2
  ex_cldr_numbers 0.3.2
  ex_money 0.8.3
  flow 0.12.0
  gen_stage 0.12.2
  gettext 0.13.1
  poison 3.1.0
```
I've upgraded to 0.8.3, and the error above still persists. Perhaps it is because I'm running ex_money within an application that is part of an umbrella? For some reason `retriever_options` is not set in state when attempting first retrieval.

**Comment by Schultzer** [comment]
@kipcole9 this happens in [#L67](https://github.com/kipcole9/money/blob/792182e000f8645f4ee0ef3effea9e0e01afab46/lib/money/exchange_rates/open_exchange_rates.ex#L67)
and it only happens on the first run because `:retriever_options` is nil
it affects our system too. maybe this should be set at compile time.

**Comment by kipcole9** [comment]
I have changed the initialisation strategy to move the initialisation out of the `OpenExchangeRatesRetriever` module and back into the `ExchangeRates` module since I think this error is a race condition.

I have updated master.  May I ask you to try using the version on master to see if that corrects the error?  In mix.exs:
```
def deps do
  {:ex_cldr, git: "https://github.com/kipcole9/money.git"
end
```
If you confirm its ok I'll update the package on hex.  

If it doesn't correct the error, may I ask you to extend the delay parameter in your `dev.exs` and try again?  That will help me confirm its a race condition or not.  On each machine I have access to today the code is working so perhaps your machines are a lot faster than mine or have a bunch more cores :-)
```
config :ex_money,
  exchange_rate_service: true,
  delay_before_first_retrieval:  500
```
Thanks for your patience and sorry for the bug.

**Comment by Schultzer** [comment]
@kipcole9 This is great, master fix the issue on our system

**Comment by blaketan** [comment]
@kipcole We're still observing the issue on our end after upgrading to 0.84
```
2017-11-10 10:29:10.630 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:68: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:51: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:45: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 100, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
2017-11-10 10:29:10.632 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:68: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:51: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:45: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 100, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
2017-11-10 10:29:10.700 [warn] Starting exchange rate retrieval service
2017-11-10 10:29:10.700 [warn] Rates will be retrieved in 100 milliseconds and then every 3600 seconds.
2017-11-10 10:29:10.701 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:68: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:51: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:45: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 100, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
iex(1)> 2017-11-10 10:29:10.815 [warn] Initialized retrieval module Money.ExchangeRates.OpenExchangeRates
2017-11-10 10:29:10.815 [warn] Starting exchange rate retrieval service
2017-11-10 10:29:10.815 [warn] Rates will be retrieved in 100 milliseconds and then every 3600 seconds.
2017-11-10 10:29:10.816 [error] GenServer Money.ExchangeRates.Retriever terminating
** (UndefinedFunctionError) function nil.url/0 is undefined (module nil is not available)
    nil.url()
    (ex_money) lib/money/exchange_rates/open_exchange_rates.ex:68: Money.ExchangeRates.OpenExchangeRates.get_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:51: Money.ExchangeRates.Retriever.retrieve_latest_rates/1
    (ex_money) lib/money/exchange_rates/exchange_rates_retriever.ex:45: Money.ExchangeRates.Retriever.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :latest
State: %Money.ExchangeRates.Config{api_module: Money.ExchangeRates.OpenExchangeRates, callback_module: Money.ExchangeRates.Callback, delay_before_first_retrieval: 100, log_levels: %{failure: :warn, info: :warn, success: :debug}, retrieve_every: 3600000, retriever_options: nil}
2017-11-10 10:29:11.323 [debug] Retrieved exchange rates successfully
```

Attempting to change the `delay_before_first_retrieval` between 1 and 1_000 parameter did not help solve the issue.

**Comment by kipcole9** [comment]
@blaketan Thanks for the update and PR.  Will merge and push right away.
